"use strict";
const canvas=document.querySelector("#stageThreeCanvas"),ctx=canvas.getContext("2d");
const homeworldBaseImage=new Image();homeworldBaseImage.src="assets/homeworld-base.png";
const levelOneBackground=new Image();levelOneBackground.src="assets/level-1-illustrated-front.png";
const levelTwoBackground=new Image();levelTwoBackground.src="assets/level-2-illustrated-front.png";
const levelThreeBackground=new Image();levelThreeBackground.src="assets/level-3-vertical-front.png";
const $=s=>document.querySelector(s),ui={debris:$("#s3Debris"),relics:$("#s3Relics"),wave:$("#s3Wave"),health:$("#s3Health"),start:$("#s3StartOverlay"),pause:$("#s3PauseOverlay"),intermission:$("#s3Intermission"),intermissionTitle:$("#s3IntermissionTitle"),end:$("#s3EndOverlay"),endTitle:$("#s3EndTitle"),endDetail:$("#s3EndDetail"),status:$("#s3Status"),next:$("#s3NextWave"),selected:$("#s3Selected"),selectedName:$("#s3SelectedName"),level:$("#s3Level"),damage:$("#s3Damage"),range:$("#s3Range"),upgrade:$("#s3Upgrade"),upgradeCost:$("#s3UpgradeCost"),relicUpgrade:$("#s3RelicUpgrade"),relicName:$("#s3RelicName"),sell:$("#s3Sell"),sellValue:$("#s3SellValue"),toast:$("#s3Toast"),controller:$("#s3ControllerStatus")};
const levelPaths={
  1:[[[70,300],[160,300],[210,292],[250,270],[290,236],[335,226],[386,226],[435,240],[472,260],[560,260],[604,286],[628,312],[700,312],[770,316],[835,318],[930,318]]],
  2:[[[69,135],[116,135],[162,135],[197,138],[225,153],[249,178],[281,190],[322,191],[359,182],[397,164],[438,156],[484,156],[519,169],[547,199],[575,219],[619,219],[662,214],[697,194],[725,182],[759,182],[794,191],[834,204],[906,204]],[[69,434],[116,434],[162,434],[194,424],[216,395],[236,362],[266,344],[303,342],[338,359],[366,388],[400,410],[444,412],[484,400],[519,379],[556,380],[591,398],[625,420],[666,429],[709,425],[756,420],[812,419],[875,419],[906,419]]],
  3:[[[94,164],[153,164],[206,169],[253,209],[284,199],[303,172],[304,118],[325,78],[359,64],[398,78],[398,241],[398,269],[421,297],[444,269],[445,116],[466,79],[502,66],[538,79],[539,241],[540,269],[568,298],[595,270],[595,112],[618,78],[655,66],[692,81],[694,162],[711,191],[749,207],[816,208],[884,209]],[[92,166],[129,164],[162,165],[199,168],[230,189],[256,214],[239,219],[221,242],[204,273],[188,309],[180,342],[184,368],[198,389],[219,412],[250,432],[279,439],[298,460],[303,494],[305,521],[323,534],[334,534],[344,518],[345,473],[345,425],[342,394],[355,366],[381,350],[406,359],[422,388],[423,431],[423,462],[432,506],[465,540],[501,552],[528,539],[546,506],[551,456],[551,405],[561,374],[584,353],[614,350],[632,368],[639,405],[641,464],[649,502],[679,527],[726,532],[788,530],[845,531],[882,531]]]
};
const levelThreeBuildZones=[
  [[178,106],[252,106],[254,168],[220,184],[180,170]],
  [[125,194],[197,194],[219,225],[200,310],[132,330],[122,225]],
  [[310,95],[372,95],[372,296],[320,296],[310,200]],
  [[470,96],[532,96],[532,296],[475,296]],
  [[622,96],[684,96],[684,296],[625,296]],
  [[350,366],[414,366],[414,565],[362,565],[350,405]],
  [[442,382],[538,382],[538,532],[504,562],[450,545]],
  [[582,366],[644,366],[644,566],[594,566],[582,424]],
  [[688,398],[790,398],[790,520],[682,520],[675,438]]
];
const levelTwoBuildZones=[
  [[220,45],[395,42],[440,62],[470,100],[460,165],[420,210],[330,210],[292,176],[238,176],[205,128]],
  [[535,50],[690,50],[760,80],[770,135],[728,192],[625,195],[575,168],[522,158],[515,92]],
  [[95,190],[270,190],[315,235],[292,335],[210,360],[105,330],[62,270]],
  [[305,252],[535,250],[582,298],[555,392],[430,408],[310,365],[288,315]],
  [[585,250],[795,250],[834,308],[800,405],[640,408],[570,355]],
  [[180,430],[375,425],[425,498],[355,595],[190,575],[145,500]],
  [[450,425],[700,420],[750,505],[685,605],[495,595],[425,515]]
];
const activePaths=()=>levelPaths[state?.level||1];
const specs={pulse:{name:"Pulse Cannon",cost:45,damage:13,range:125,rate:.42,color:"#68d6c7",relic:"Pulse Relic Tree",relicDescription:"Choose Rapid Ordnance or Heavy Ordnance for this cannon."},rail:{name:"Rail Lance",cost:75,damage:48,range:175,rate:1.5,color:"#f2c45b",relic:"Phase-Piercing Slug",relicDescription:"+80% damage and +30 range. Every shot penetrates all ships in its line."},cryo:{name:"Cryo Array",cost:65,damage:7,range:115,rate:.75,color:"#88bfff",relic:"Absolute-Zero Field",relicDescription:"+25 range. Ships inside the field are reduced to 20% speed."}};
const pulseBranches={rapid:[{name:"Hypercycling",description:"Fires 45% faster."},{name:"Accelerated Bolts",description:"Projectiles travel 100% faster."},{name:"Antares Horizon",description:"Extends attack range by 90."}],heavy:[{name:"Overcharged Bolts",description:"Fires 35% slower; slow projectiles deal double damage."},{name:"Impact Bloom",description:"Fires 50% slower; hits splash 65% damage across a larger area."},{name:"Devastation Bomb",description:"Fires 100% slower; enormous blasts deal extreme damage across a huge area."}]};
const railBranches={siege:[{name:"Accelerator Coils",description:"Adds 45 range and 35% damage."},{name:"Phase-Piercing Slug",description:"Shots penetrate every ship in their firing line."},{name:"Planet Cracker",description:"Each penetrated ship erupts in a damaging blast."}],barrage:[{name:"Quickloader",description:"Fires 30% faster."},{name:"Split Rails",description:"Shots fork to a second target for 60% damage."},{name:"Storm Lance",description:"Every third attack fires a three-shot volley."}]};
const cryoBranches={absolute:[{name:"Deep Chill",description:"Reduces affected ships to 40% speed."},{name:"Permafrost",description:"The slow persists for 1.2 seconds after leaving range."},{name:"Absolute Zero",description:"Periodically freezes affected ships completely."}],shatter:[{name:"Thermal Fracture",description:"Deals 50% more damage to chilled ships."},{name:"Brittle Hull",description:"Chilled ships take 25% more damage from every tower."},{name:"Cryo Nova",description:"Chilled ships explode when destroyed, damaging and slowing nearby ships."}]};
let state,towers,enemies,shots,drops,aoeBlasts,stars,last=0,toastTimer=0;
let controllerActionMode=null;
let lastATap=-Infinity,aTapTimer=0;
let recycleConfirmTower=null,recycleConfirmTimer=0;
let stageMenuIndex=0;
const controller={x:330,y:430,screenX:0,screenY:0,onCanvas:true,initialized:false,buttons:[],connected:false,menuAxisHeld:false,firstWaveLaunchCentered:false};
function reset(){state={started:false,paused:false,intermission:false,over:false,level:1,wave:1,debris:100,relics:0,health:20,build:"pulse",selected:null,spawning:0,spawnTimer:0,waveActive:false,kills:0};towers=[];enemies=[];shots=[];drops=[];aoeBlasts=[];stars=Array.from({length:100},()=>({x:Math.random()*960,y:Math.random()*640,r:Math.random()*1.7+.3,a:Math.random()*.6+.2}));updateUI();}
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function getCanvasContentRect(){const box=canvas.getBoundingClientRect(),sourceRatio=canvas.width/canvas.height,boxRatio=box.width/box.height;if(boxRatio>sourceRatio){const height=box.height,width=height*sourceRatio;return {left:box.left+(box.width-width)/2,top:box.top,width,height,right:box.left+(box.width+width)/2,bottom:box.bottom}}const width=box.width,height=width/sourceRatio;return {left:box.left,top:box.top+(box.height-height)/2,width,height,right:box.right,bottom:box.top+(box.height+height)/2}}
function isNearActivePath(p){const clearance=state.level===3?28:52;for(const route of activePaths())for(let i=0;i<route.length-1;i++){const a={x:route[i][0],y:route[i][1]},b={x:route[i+1][0],y:route[i+1][1]},l2=(b.x-a.x)**2+(b.y-a.y)**2,q=clamp(((p.x-a.x)*(b.x-a.x)+(p.y-a.y)*(b.y-a.y))/l2,0,1);if(Math.hypot(p.x-(a.x+q*(b.x-a.x)),p.y-(a.y+q*(b.y-a.y)))<clearance)return true}return false}
function isNearActivePathClearance(p,clearance){for(const route of activePaths())for(let i=0;i<route.length-1;i++){const a={x:route[i][0],y:route[i][1]},b={x:route[i+1][0],y:route[i+1][1]},l2=(b.x-a.x)**2+(b.y-a.y)**2,q=clamp(((p.x-a.x)*(b.x-a.x)+(p.y-a.y)*(b.y-a.y))/l2,0,1);if(Math.hypot(p.x-(a.x+q*(b.x-a.x)),p.y-(a.y+q*(b.y-a.y)))<clearance)return true}return false}
function pointInPolygon(p,polygon){let inside=false;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const [xi,yi]=polygon[i],[xj,yj]=polygon[j];if((yi>p.y)!==(yj>p.y)&&p.x<(xj-xi)*(p.y-yi)/(yj-yi)+xi)inside=!inside}return inside}
function drawHexField(polygon){ctx.save();ctx.beginPath();polygon.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.clip();ctx.fillStyle="rgba(15,91,105,.22)";ctx.fillRect(0,0,960,640);ctx.strokeStyle="rgba(74,220,225,.2)";ctx.lineWidth=1;const size=14,h=Math.sqrt(3)*size;for(let row=-1;row<30;row++)for(let col=-1;col<45;col++){const x=col*size*1.5,y=row*h+(col%2?h/2:0);ctx.beginPath();for(let k=0;k<6;k++){const a=Math.PI/3*k,px=x+size*Math.cos(a),py=y+size*Math.sin(a);k?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath();ctx.stroke()}ctx.restore();ctx.strokeStyle="rgba(77,232,230,.85)";ctx.lineWidth=2;ctx.shadowBlur=8;ctx.shadowColor="#29d9df";ctx.beginPath();polygon.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.stroke();ctx.shadowBlur=0}
function drawSpaceBackdrop(){const nebula=ctx.createRadialGradient(state.level===3?720:780,state.level===2?160:440,20,state.level===3?720:780,state.level===2?160:440,430);nebula.addColorStop(0,state.level===1?"rgba(32,83,142,.34)":state.level===2?"rgba(20,107,118,.25)":"rgba(93,35,132,.25)");nebula.addColorStop(1,"rgba(2,5,14,0)");ctx.fillStyle=nebula;ctx.fillRect(0,0,960,640);stars.forEach(s=>{ctx.globalAlpha=s.a;ctx.fillStyle="#dff7ff";ctx.fillRect(s.x,s.y,s.r,s.r)});ctx.globalAlpha=1;for(let i=0;i<18;i++){const x=(i*137+state.level*71)%960,y=(i*89+state.level*43)%640,r=4+(i*7)%13;ctx.fillStyle="rgba(24,35,48,.7)";ctx.strokeStyle="rgba(91,112,127,.34)";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x-r,y);for(let k=1;k<7;k++){const a=k*Math.PI*2/7,rr=r*(.72+(k%3)*.15);ctx.lineTo(x+Math.cos(a)*rr,y+Math.sin(a)*rr)}ctx.closePath();ctx.fill();ctx.stroke()}}
function drawPortal(x,y){ctx.save();for(let i=4;i>0;i--){ctx.strokeStyle=`rgba(246,72,199,${.18+i*.14})`;ctx.lineWidth=5;ctx.shadowBlur=15;ctx.shadowColor="#ff45c5";ctx.beginPath();ctx.ellipse(x,y,13+i*8,20+i*10,0,0,Math.PI*2);ctx.stroke()}ctx.fillStyle="rgba(255,55,193,.18)";ctx.beginPath();ctx.ellipse(x,y,20,34,0,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawForwardBase(x,y,label){ctx.save();ctx.translate(x,y);ctx.fillStyle="rgba(11,43,54,.9)";ctx.strokeStyle="#53ded6";ctx.lineWidth=3;ctx.shadowBlur=12;ctx.shadowColor="#2ddfd7";ctx.beginPath();ctx.arc(0,0,38,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.beginPath();ctx.arc(0,0,20,0,Math.PI*2);ctx.stroke();for(let i=0;i<8;i++){ctx.rotate(Math.PI/4);ctx.fillRect(33,-4,15,8)}ctx.shadowBlur=0;ctx.fillStyle="#c9ffff";ctx.font="700 10px sans-serif";ctx.textAlign="center";ctx.fillText(label,0,58);ctx.restore()}
function towerStats(t){const s=specs[t.type],m=Math.pow(1.18,t.level-1);let damage=s.damage*m,range=s.range+Math.min(90,(t.level-1)*9),rate=s.rate*Math.max(.3,Math.pow(.91,t.level-1));if(t.type==="pulse"&&t.relicPath==="rapid"){if(t.relicTier>=1)rate*=.55;if(t.relicTier>=3)range+=90}if(t.type==="pulse"&&t.relicPath==="heavy"){if(t.relicTier>=1){damage*=2;rate*=t.relicTier>=3?2:t.relicTier>=2?1.5:1.35}if(t.relicTier>=3)damage*=1.6}if(t.type==="rail"&&t.relicPath==="siege"&&t.relicTier>=1){damage*=1.35;range+=45}if(t.type==="rail"&&t.relicPath==="barrage"&&t.relicTier>=1)rate*=.7;if(t.type==="cryo"&&t.relicPath==="shatter"&&t.relicTier>=1)damage*=1.5;return {damage,range,rate}}
function enemyPoint(e){const route=activePaths()[e.route||0];if(e.seg>=route.length-1)return{x:route.at(-1)[0],y:route.at(-1)[1]};const a=route[e.seg],b=route[e.seg+1];return{x:a[0]+(b[0]-a[0])*e.t,y:a[1]+(b[1]-a[1])*e.t}}
function spawnEnemy(){state.spawnedThisWave++;const routes=activePaths(),flying=state.level===3&&state.wave>=5&&state.spawnedThisWave%12===0,routeIndex=state.level>1?(state.spawnedThisWave-1)%routes.length:0,route=routes[routeIndex],boss=!flying&&state.wave%10===0&&state.spawning===1,armored=!flying&&!boss&&state.wave>=3&&state.spawnedThisWave%4===0,interceptor=!flying&&!boss&&state.wave>=4&&state.spawnedThisWave%5===0;const earlyWave=Math.min(state.wave,10),lateWave=Math.max(0,state.wave-10),waveHealth=56*Math.pow(1.30,earlyWave-1)*Math.pow(1.10,lateWave),healthMultiplier=flying?2.6:boss?5:armored?2.2:interceptor?.78:1,hp=waveHealth*healthMultiplier*(.95+Math.random()*.12),speed=flying?32+state.wave*1.1:boss?35+state.wave:(51+state.wave*2.2)*(interceptor?1.5:armored?.8:1),x=flying?-28:route[0][0],y=flying?590:route[0][1];enemies.push({route:routeIndex,seg:0,t:0,x,y,hp,maxHp:hp,speed,reward:flying?Math.round(18+state.wave*2):boss?100+state.wave*5:Math.round((8+state.wave*1.4)*(armored?1.65:interceptor?1.25:1)),boss,armored,interceptor,flying,flightProgress:0,breachDamage:flying?3:boss?7:armored?3:1,slow:0,spawnAge:0});}
function beginWave(){if(state.waveActive||state.over)return;state.intermission=false;ui.intermission.hidden=true;state.waveActive=true;state.spawnedThisWave=0;const baseEnemyCount=7+state.wave*2;state.spawning=state.level===3?Math.ceil(baseEnemyCount*1.3):baseEnemyCount;state.spawnTimer=.2;ui.next.textContent="Launch Next Wave (A)";ui.next.hidden=true;ui.status.textContent=`Level ${state.level}, Wave ${state.wave}: ${state.spawning} contacts inbound. Enemy hull growth ${state.wave>10?"+10%":"+30%"}.`;}
function endGame(win){state.over=true;ui.end.hidden=false;ui.endTitle.textContent=win?"Alien Advance Broken":state.level===1?"The Relic Has Fallen":"The Frontline Collapsed";ui.endDetail.textContent=win?`All three fronts secured · ${state.kills} ships destroyed`:`Level ${state.level}, Wave ${state.wave} · ${state.kills} ships destroyed`;}
function showRelicDropNotification(){const board=$(".stage-three-board");const notice=document.createElement("div");notice.className="s3-relic-drop-alert";notice.innerHTML="<span>Relic signal</span><strong>Core detected on the battlefield</strong>";board.append(notice);setTimeout(()=>notice.classList.add("is-fading"),1700);setTimeout(()=>notice.remove(),2300)}
function killEnemy(e){state.kills++;state.debris+=e.reward;const levelOneBoost=state.level===1,chance=e.armored?(levelOneBoost ? .30 : .25):e.interceptor?(levelOneBoost ? .045 : .03):(levelOneBoost ? .022 : .015);if(e.boss||Math.random()<chance){drops.push({x:e.x+18,y:e.y-8,type:"relic",value:1,life:18,bob:1});showRelicDropNotification()}}
function triggerCryoNova(source){const radius=85,damage=source.cryoNovaDamage||20;aoeBlasts.push({x:source.x,y:source.y,radius,life:.6,maxLife:.6,tier:2,cryo:true});for(const enemy of enemies){if(enemy.dead||enemy===source||dist(enemy,source)>=radius)continue;enemy.hp-=damage;enemy.slow=Math.max(enemy.slow,1);enemy.slowFactor=.35;if(enemy.hp<=0){enemy.dead=true;killEnemy(enemy)}}}
 function update(dt){if(!state.started||state.paused||state.intermission||state.over)return;if(state.waveActive&&state.spawning>0){state.spawnTimer-=dt;if(state.spawnTimer<=0){spawnEnemy();state.spawning--;const baseSpawnInterval=Math.max(.36,1.05-state.wave*.045);state.spawnTimer=state.level===3?baseSpawnInterval*.85:baseSpawnInterval}}
 for(const e of enemies){e.spawnAge=(e.spawnAge||0)+dt;e.slow=Math.max(0,e.slow-dt);e.brittle=Math.max(0,(e.brittle||0)-dt);e.cryoNova=Math.max(0,(e.cryoNova||0)-dt);e.freeze=Math.max(0,(e.freeze||0)-dt);let move=e.freeze>0?0:e.speed*(e.slow>0?(e.slowFactor||.54):1)*dt;e.slowFactor=.54;if(e.flying){const targetX=925,targetY=530,dx=targetX-e.x,dy=targetY-e.y,distance=Math.hypot(dx,dy);if(distance<=move+8){e.x=targetX;e.y=targetY;e.dead=true;state.health-=e.breachDamage}else if(distance){e.x+=dx/distance*move;e.y+=dy/distance*move;e.flightProgress=clamp(1-distance/955,0,1);e.t=e.flightProgress}}else{const route=activePaths()[e.route||0];while(move>0&&e.seg<route.length-1){const a=route[e.seg],b=route[e.seg+1],len=Math.hypot(b[0]-a[0],b[1]-a[1]),left=(1-e.t)*len;if(move<left){e.t+=move/len;move=0}else{move-=left;e.seg++;e.t=0}}const p=enemyPoint(e);e.x=p.x;e.y=p.y;if(e.seg>=route.length-1){e.dead=true;state.health-=e.breachDamage}}}
 for(const t of towers){t.cool-=dt;t.freezeCooldown=Math.max(0,(t.freezeCooldown||0)-dt);const st=towerStats(t),targets=enemies.filter(e=>!e.dead&&dist(t,e)<=st.range).sort((a,b)=>(b.seg+b.t)-(a.seg+a.t));if(t.type==="cryo")targets.forEach(e=>{const absolute=t.relicPath==="absolute",shatter=t.relicPath==="shatter";e.slow=Math.max(e.slow,absolute&&t.relicTier>=2?1.2:.22);e.slowFactor=absolute&&t.relicTier>=1?.4:.54;if(shatter&&t.relicTier>=2)e.brittle=Math.max(e.brittle,.3);if(shatter&&t.relicTier>=3){e.cryoNova=Math.max(e.cryoNova,.3);e.cryoNovaDamage=Math.max(e.cryoNovaDamage||0,st.damage*2.5)}});if(t.type==="cryo"&&t.relicPath==="absolute"&&t.relicTier>=3&&targets.length&&t.freezeCooldown<=0){targets.forEach(e=>e.freeze=Math.max(e.freeze,.8));t.freezeCooldown=4}if(t.cool<=0&&targets.length){const target=targets[0];t.cool=st.rate;let speed=t.type==="rail"?680:420;if(t.type==="pulse"&&t.relicPath==="rapid"&&t.relicTier>=2)speed*=2;if(t.type==="pulse"&&t.relicPath==="heavy")speed*=t.relicTier>=3?.42:.65;const makeShot=(shotTarget,scale=1)=>({x:t.x,y:t.y,originX:t.x,originY:t.y,target:shotTarget,damage:st.damage*scale,color:specs[t.type].color,speed,type:t.type,relic:t.relic,relicPath:t.relicPath,relicTier:t.relicTier||0,fork:scale<1,seed:Math.random()*999});shots.push(makeShot(target));if(t.type==="rail"&&t.relicPath==="barrage"&&t.relicTier>=2&&targets[1])shots.push(makeShot(targets[1],.6));if(t.type==="rail"&&t.relicPath==="barrage"&&t.relicTier>=3){t.stormCount=((t.stormCount||0)+1)%3;if(t.stormCount===0)shots.push(makeShot(targets[2]||target))}}}
 for(const s of shots){if(s.target.dead){s.dead=true;continue}const d=dist(s,s.target),step=s.speed*dt;if(d<=step+6){const hit=(enemy,damage)=>{if(enemy.dead)return;enemy.hp-=damage*(enemy.brittle>0?1.25:1);if(enemy.hp<=0){const nova=enemy.cryoNova>0;enemy.dead=true;killEnemy(enemy);if(nova)triggerCryoNova(enemy)}};if(s.type==="rail"&&s.relicPath==="siege"&&s.relicTier>=2){const dx=s.target.x-s.originX,dy=s.target.y-s.originY,len=Math.hypot(dx,dy)||1;for(const enemy of enemies){const projection=((enemy.x-s.originX)*dx+(enemy.y-s.originY)*dy)/len,perpendicular=Math.abs((enemy.x-s.originX)*dy-(enemy.y-s.originY)*dx)/len;if(projection>=0&&perpendicular<20){hit(enemy,s.damage);if(s.relicTier>=3){aoeBlasts.push({x:enemy.x,y:enemy.y,radius:48,life:.4,maxLife:.4,tier:2});for(const nearby of enemies)if(!nearby.dead&&nearby!==enemy&&dist(nearby,enemy)<48)hit(nearby,s.damage*.35)}}}}else{hit(s.target,s.damage);if(s.type==="pulse"&&s.relicPath==="heavy"&&s.relicTier>=2){const radius=s.relicTier>=3?125:65,scale=s.relicTier>=3?.9:.65;aoeBlasts.push({x:s.target.x,y:s.target.y,radius,life:.52,maxLife:.52,tier:s.relicTier});for(const enemy of enemies)if(!enemy.dead&&enemy!==s.target&&dist(enemy,s.target)<radius)hit(enemy,s.damage*scale)}}s.dead=true}else{s.x+=(s.target.x-s.x)/d*step;s.y+=(s.target.y-s.y)/d*step}}
 drops.forEach(d=>d.life-=dt);aoeBlasts.forEach(b=>b.life-=dt);enemies=enemies.filter(e=>!e.dead);shots=shots.filter(s=>!s.dead);drops=drops.filter(d=>d.life>0);aoeBlasts=aoeBlasts.filter(b=>b.life>0);if(state.health<=0)endGame(false);if(state.waveActive&&state.spawning===0&&!enemies.length){state.waveActive=false;shots.length=0;aoeBlasts.length=0;if(state.wave>=20){if(state.level<3)advanceLevel();else endGame(true)}else{state.wave++;state.intermission=true;state.debris+=15+Math.floor(state.wave/5)*5;if(!state.selected&&towers.length)state.selected=towers[0];ui.intermissionTitle.textContent=`Prepare for Wave ${state.wave}`;ui.intermission.hidden=true;ui.status.textContent=`Wave cleared — prepare for Wave ${state.wave}. Select a tower and purchase upgrades.`;ui.next.hidden=false}}updateUI();}
function advanceLevel(){state.level++;state.wave=1;state.debris=100;state.relics=0;state.health=20;state.intermission=true;state.selected=null;state.build="pulse";towers=[];enemies=[];shots=[];drops=[];aoeBlasts=[];document.querySelectorAll(".s3-build").forEach(b=>b.classList.toggle("is-active",b.dataset.tower==="pulse"));prepareFirstWave(false)}
function prepareFirstWave(debug=false){state.intermission=true;state.waveActive=false;state.spawning=0;state.spawnTimer=0;controller.firstWaveLaunchCentered=false;ui.intermission.hidden=true;ui.next.textContent=`Launch Level ${state.level} Wave 1 (A)`;ui.next.hidden=false;ui.status.textContent=debug?`DEBUG · Level ${state.level}, Wave 1 ready. Build defenses, then press A to launch.`:state.level===1?"Level 1: Homeworld approach ready. Build defenses, then press A to launch Wave 1.":state.level===2?"Level 2: Outward Front ready. Build a fresh defense grid, then press A to launch Wave 1.":"Level 3: Deeper Front ready. Build inside the cyan zones, then press A to launch Wave 1.";updateUI();requestAnimationFrame(()=>{if(controller.connected){centerControllerOnElement(ui.next);controller.firstWaveLaunchCentered=true}})}
function startLevelThreeDebug(){state.level=3;state.wave=1;state.debris=100;state.relics=0;state.health=20;state.started=true;state.paused=false;state.intermission=true;state.over=false;state.selected=null;state.build="pulse";state.spawning=0;state.spawnTimer=0;state.waveActive=false;towers=[];enemies=[];shots=[];drops=[];aoeBlasts=[];document.querySelectorAll(".s3-build").forEach(b=>b.classList.toggle("is-active",b.dataset.tower==="pulse"));ui.start.hidden=true;ui.end.hidden=true;ui.pause.hidden=true;prepareFirstWave(true)}
function startDebugLevel(level){state.level=level;state.wave=1;state.debris=100;state.relics=0;state.health=20;state.started=true;state.paused=false;state.intermission=true;state.over=false;state.selected=null;state.build="pulse";state.spawning=0;state.spawnTimer=0;state.waveActive=false;towers=[];enemies=[];shots=[];drops=[];aoeBlasts=[];resetRecycleConfirm();document.querySelectorAll(".s3-build").forEach(b=>b.classList.toggle("is-active",b.dataset.tower==="pulse"));ui.start.hidden=true;ui.end.hidden=true;ui.pause.hidden=true;prepareFirstWave(true)}
function drawPath(){ctx.lineCap="round";ctx.lineJoin="round";for(const route of activePaths()){ctx.strokeStyle="#101820";ctx.lineWidth=76;ctx.shadowBlur=10;ctx.shadowColor="rgba(42,202,218,.2)";ctx.beginPath();route.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle="#29495b";ctx.lineWidth=62;ctx.stroke();ctx.strokeStyle="#588096";ctx.lineWidth=2;ctx.setLineDash([14,16]);ctx.stroke();ctx.setLineDash([])}}
function enemyHeading(e){if(e.flying){const targetX=925,targetY=530;return Math.atan2(targetY-e.y,targetX-e.x)}const route=activePaths()[e.route||0],a=route[Math.min(e.seg,route.length-2)],b=route[Math.min(e.seg+1,route.length-1)];return Math.atan2(b[1]-a[1],b[0]-a[0])}
function drawTower(t){const st=towerStats(t),color=specs[t.type].color,selected=state.selected===t,pulse=performance.now()/500;if(selected){ctx.fillStyle="rgba(104,214,199,.08)";ctx.strokeStyle="rgba(104,214,199,.35)";ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(t.x,t.y,st.range,0,Math.PI*2);ctx.fill();ctx.stroke()}ctx.save();ctx.translate(t.x,t.y);ctx.shadowBlur=14;ctx.shadowColor=color;ctx.fillStyle="rgba(4,16,25,.78)";ctx.strokeStyle="rgba(143,240,255,.34)";ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,24,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle=color;ctx.lineWidth=2.5;ctx.beginPath();ctx.arc(0,0,16,0,Math.PI*2);ctx.stroke();for(let i=0;i<6;i++){ctx.rotate(Math.PI/3);ctx.fillStyle="rgba(8,31,44,.95)";ctx.strokeStyle="rgba(111,231,236,.45)";ctx.beginPath();ctx.roundRect?ctx.roundRect(13,-4,12,8,3):ctx.rect(13,-4,12,8);ctx.fill();ctx.stroke()}ctx.rotate(-Math.PI*2);const barrelAngle=t.type==="rail"?-.08:t.type==="cryo"?0:.08;ctx.rotate(barrelAngle);if(t.type==="pulse"){ctx.fillStyle="#0c1f2b";ctx.strokeStyle=color;ctx.lineWidth=3;ctx.beginPath();ctx.roundRect?ctx.roundRect(-6,-31,12,28,5):ctx.rect(-6,-31,12,28);ctx.fill();ctx.stroke();ctx.fillStyle=color;ctx.beginPath();ctx.arc(0,-33,5+Math.sin(pulse)*1.2,0,Math.PI*2);ctx.fill()}else if(t.type==="rail"){ctx.strokeStyle=color;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-7,-4);ctx.lineTo(-7,-38);ctx.moveTo(7,-4);ctx.lineTo(7,-38);ctx.stroke();ctx.fillStyle="#121923";ctx.strokeStyle="#ffe59d";ctx.lineWidth=2;ctx.fillRect(-12,-35,24,7);ctx.strokeRect(-12,-35,24,7)}else{ctx.strokeStyle=color;ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,-19,14,Math.PI*.15,Math.PI*.85);ctx.stroke();ctx.beginPath();ctx.arc(0,-19,8,Math.PI*.15,Math.PI*.85);ctx.stroke();ctx.fillStyle="rgba(136,191,255,.45)";ctx.beginPath();ctx.arc(0,-18,9+Math.sin(pulse)*1.5,0,Math.PI*2);ctx.fill()}ctx.rotate(-barrelAngle);ctx.fillStyle="#07111a";ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,10,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=color;ctx.beginPath();ctx.arc(0,0,3.5,0,Math.PI*2);ctx.fill();if(t.relic){ctx.strokeStyle="#fff09b";ctx.lineWidth=2;ctx.setLineDash([5,5]);ctx.beginPath();ctx.arc(0,0,30,0,Math.PI*2);ctx.stroke();ctx.setLineDash([])}ctx.restore()}
function drawEnemyShip(e){const angle=enemyHeading(e),spawnProgress=clamp((e.spawnAge||0)/.55,0,1),warpAlpha=1-spawnProgress,baseScale=e.boss?1.45:e.armored?1.22:e.interceptor?.85:e.flying?1.15:1,scale=baseScale*(.35+.65*spawnProgress),color=e.flying?"#d66cff":e.boss?"#f2c45b":e.armored?"#b082d6":e.interceptor?"#ff9a68":"#f06d72",core=e.flying?"#f1c8ff":e.boss?"#fff2a8":"#ffd4d6";ctx.save();if(warpAlpha>0){ctx.globalAlpha=warpAlpha;ctx.strokeStyle="rgba(255,72,200,.9)";ctx.lineWidth=2+warpAlpha*3;ctx.shadowBlur=18;ctx.shadowColor="#ff45c5";ctx.beginPath();ctx.arc(e.x,e.y,10+26*spawnProgress,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(e.x,e.y,22-10*spawnProgress,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;ctx.shadowBlur=0}ctx.translate(e.x,e.y);ctx.rotate(angle);ctx.scale(scale,scale);ctx.globalAlpha=.45+.55*spawnProgress;ctx.shadowBlur=10;ctx.shadowColor=color;ctx.fillStyle="rgba(0,0,0,.34)";ctx.beginPath();ctx.ellipse(-3,5,21,8,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=color;ctx.strokeStyle="rgba(255,255,255,.6)";ctx.lineWidth=1.4;ctx.beginPath();if(e.flying){ctx.moveTo(20,0);ctx.lineTo(2,-10);ctx.lineTo(-10,-18);ctx.lineTo(-7,-6);ctx.lineTo(-22,0);ctx.lineTo(-7,6);ctx.lineTo(-10,18);ctx.lineTo(2,10)}else{ctx.moveTo(22,0);ctx.lineTo(3,-11);ctx.lineTo(-16,-8);ctx.lineTo(-9,0);ctx.lineTo(-16,8);ctx.lineTo(3,11)}ctx.closePath();ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle="rgba(12,10,22,.65)";ctx.beginPath();ctx.ellipse(0,0,10,5.5,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=core;ctx.beginPath();ctx.arc(6,0,3.5,0,Math.PI*2);ctx.fill();if(e.armored||e.boss){ctx.strokeStyle="#ead7ff";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-6,-9);ctx.lineTo(8,-4);ctx.lineTo(8,4);ctx.lineTo(-6,9);ctx.stroke()}ctx.globalAlpha=.55;ctx.fillStyle=e.flying?"#d66cff":"#69e9ff";ctx.beginPath();ctx.moveTo(-18,-5);ctx.lineTo(-32,0);ctx.lineTo(-18,5);ctx.fill();ctx.globalAlpha=1;ctx.restore();ctx.globalAlpha=1;ctx.fillStyle="rgba(37,19,26,.82)";ctx.fillRect(e.x-17,e.y-25,34,5);ctx.fillStyle="#68d6c7";ctx.fillRect(e.x-17,e.y-25,34*clamp(e.hp/e.maxHp,0,1),5)}
function drawShot(s){const angle=Math.atan2(s.target.y-s.y,s.target.x-s.x),heavy=s.type==="pulse"&&s.relicPath==="heavy",now=performance.now()/80+(s.seed||0);if(s.type==="rail"){const fork=s.relicPath==="barrage"&&s.relicTier>=2,boltLength=fork?44:58;ctx.save();ctx.translate(s.x,s.y);ctx.rotate(angle);ctx.shadowBlur=fork?22:16;ctx.shadowColor=fork?"#8ff7ff":"#f7d86c";for(let pass=0;pass<2;pass++){ctx.strokeStyle=pass? (fork?"#e9ffff":"#fff7b8") : (fork?"rgba(84,238,255,.72)":"rgba(242,196,91,.75)");ctx.lineWidth=pass?2:6;ctx.beginPath();ctx.moveTo(-boltLength,0);const segments=6;for(let i=1;i<=segments;i++){const x=-boltLength+(boltLength*1.25)*i/segments,y=Math.sin(now+i*2.13)*5*(i%2?-1:1);ctx.lineTo(x,y)}ctx.stroke()}if(fork){for(let branch=0;branch<3;branch++){const start=-22+branch*14,dir=branch%2?-1:1;ctx.strokeStyle="rgba(160,250,255,.82)";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(start,Math.sin(now+branch)*3);ctx.lineTo(start+12,dir*(10+branch*3));ctx.lineTo(start+24,dir*(4+Math.sin(now+branch)*5));ctx.stroke()}}ctx.restore();ctx.shadowBlur=0;return}if(s.type==="cryo"){ctx.save();ctx.translate(s.x,s.y);ctx.rotate(angle);ctx.shadowBlur=14;ctx.shadowColor="#88bfff";ctx.fillStyle="rgba(190,225,255,.95)";ctx.strokeStyle="#88bfff";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(14,0);ctx.lineTo(0,-7);ctx.lineTo(-14,0);ctx.lineTo(0,7);ctx.closePath();ctx.fill();ctx.stroke();ctx.strokeStyle="rgba(190,235,255,.65)";ctx.beginPath();ctx.moveTo(-26,0);ctx.lineTo(-8,0);ctx.stroke();ctx.restore();ctx.shadowBlur=0;return}const radius=heavy&&s.relicTier>=3?10:heavy?7:4;ctx.save();ctx.translate(s.x,s.y);ctx.rotate(angle);ctx.shadowBlur=heavy?22:12;ctx.shadowColor=heavy?"#ff8b45":s.color;if(heavy){ctx.fillStyle="#ffb35c";ctx.strokeStyle="#fff0b0";ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,radius,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.strokeStyle="rgba(255,168,74,.72)";ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-radius*4,0);ctx.lineTo(-radius,0);ctx.stroke()}else{ctx.strokeStyle=s.color;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-20,0);ctx.lineTo(4,0);ctx.stroke();ctx.fillStyle="#dff";ctx.beginPath();ctx.arc(6,0,radius,0,Math.PI*2);ctx.fill();ctx.fillStyle=s.color;ctx.beginPath();ctx.arc(6,0,radius*1.7,0,Math.PI*2);ctx.fill()}ctx.restore();ctx.shadowBlur=0}
function draw(){ctx.fillStyle="#030711";ctx.fillRect(0,0,960,640);const illustratedLevelOne=state.level===1&&levelOneBackground.complete&&levelOneBackground.naturalWidth,illustratedLevelTwo=state.level===2&&levelTwoBackground.complete&&levelTwoBackground.naturalWidth,illustratedLevelThree=state.level===3&&levelThreeBackground.complete&&levelThreeBackground.naturalWidth;if(illustratedLevelOne)ctx.drawImage(levelOneBackground,0,0,960,640);else if(illustratedLevelTwo)ctx.drawImage(levelTwoBackground,0,0,960,640);else if(illustratedLevelThree)ctx.drawImage(levelThreeBackground,0,0,960,640);else{drawSpaceBackdrop();if(state.level===3)levelThreeBuildZones.forEach(drawHexField);drawPath()}if(state.level===1&&!illustratedLevelOne){drawPortal(0,95);if(homeworldBaseImage.complete&&homeworldBaseImage.naturalWidth)ctx.drawImage(homeworldBaseImage,765,365,270,270);else drawForwardBase(900,500,"HOMEWORLD BASE")}else if(state.level===2&&!illustratedLevelTwo){drawPortal(0,125);drawPortal(0,515);drawForwardBase(930,245,"UPPER FRONT");drawForwardBase(930,395,"LOWER FRONT")}else if(state.level===3&&!illustratedLevelThree){drawPortal(8,110);drawForwardBase(925,302,"UPPER FORWARD BASE");drawForwardBase(925,478,"LOWER FORWARD BASE")}
 towers.forEach(drawTower);
 enemies.forEach(drawEnemyShip);
 shots.forEach(drawShot);aoeBlasts.forEach(b=>{const progress=1-b.life/b.maxLife,radius=b.radius*(.18+.82*progress),alpha=1-progress;ctx.fillStyle=`rgba(255,111,48,${alpha*.2})`;ctx.strokeStyle=`rgba(255,190,92,${alpha*.9})`;ctx.lineWidth=b.tier>=3?7:4;ctx.beginPath();ctx.arc(b.x,b.y,radius,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.strokeStyle=`rgba(255,245,190,${alpha*.7})`;ctx.lineWidth=2;ctx.beginPath();ctx.arc(b.x,b.y,radius*.62,0,Math.PI*2);ctx.stroke()});drops.forEach(d=>{const y=d.y+Math.sin(performance.now()/250+d.bob)*4;ctx.shadowBlur=16;ctx.shadowColor=d.type==="relic"?"#d895ff":"#68d6c7";ctx.fillStyle=d.type==="relic"?"#d895ff":"#79e7d1";ctx.beginPath();if(d.type==="relic"){ctx.moveTo(d.x,y-9);ctx.lineTo(d.x+8,y);ctx.lineTo(d.x,y+9);ctx.lineTo(d.x-8,y)}else ctx.arc(d.x,y,7,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0});}
function setBuildType(type){state.build=type;document.querySelectorAll(".s3-build").forEach(x=>x.classList.toggle("is-active",x.dataset.tower===type));toast(`${specs[type].name} selected`)}
function ensureControllerCursor(){let cursor=$("#s3GamepadCursor");if(cursor)return cursor;cursor=document.createElement("div");cursor.id="s3GamepadCursor";cursor.setAttribute("aria-hidden","true");document.body.append(cursor);return cursor}
function positionControllerCursor(){const cursor=ensureControllerCursor();cursor.hidden=!controller.connected;cursor.style.transform=`translate(${controller.screenX}px,${controller.screenY}px) translate(-50%,-50%)`;const r=getCanvasContentRect();controller.onCanvas=controller.screenX>=r.left&&controller.screenX<=r.right&&controller.screenY>=r.top&&controller.screenY<=r.bottom;if(controller.onCanvas){controller.x=(controller.screenX-r.left)*960/r.width;controller.y=(controller.screenY-r.top)*640/r.height}}
function centerControllerOnElement(element){if(!element)return;const box=element.getBoundingClientRect();controller.screenX=box.left+box.width/2;controller.screenY=box.top+box.height/2;positionControllerCursor()}
function stageMenuButtons(){return Array.from(document.querySelectorAll("#s3StartButton,.s3-debug-button")).filter(button=>button&&button.offsetParent!==null&&!button.disabled)}
function updateStageMenuSelection(){const buttons=stageMenuButtons();if(!buttons.length)return;stageMenuIndex=clamp(stageMenuIndex,0,buttons.length-1);buttons.forEach((button,index)=>button.classList.toggle("is-controller-selected",index===stageMenuIndex));const selected=buttons[stageMenuIndex];selected.focus?.({preventScroll:true});if(ui.controller&&controller.connected&&!state.started)ui.controller.textContent="Controller: D-pad / stick chooses menu · A selects"}
function moveStageMenu(delta){const buttons=stageMenuButtons();if(!buttons.length)return;stageMenuIndex=(stageMenuIndex+delta+buttons.length)%buttons.length;updateStageMenuSelection()}
function activateStageMenu(){const buttons=stageMenuButtons();if(!buttons.length)return;updateStageMenuSelection();buttons[stageMenuIndex].click()}
function cycleTower(direction){if(!towers.length){toast("No towers built yet");return}const current=towers.indexOf(state.selected),index=(current+direction+towers.length)%towers.length;state.selected=towers[index];controller.x=state.selected.x;controller.y=state.selected.y;updateUI();const r=getCanvasContentRect();controller.screenX=r.left+controller.x/960*r.width;controller.screenY=r.top+controller.y/640*r.height;positionControllerCursor()}
function controllerBoardAction(mode,screenX=controller.screenX,screenY=controller.screenY){const beforeSelection=state.selected,beforeTowerCount=towers.length;controllerActionMode=mode;canvas.dispatchEvent(new MouseEvent("click",{clientX:screenX,clientY:screenY,bubbles:true}));controllerActionMode=null;const r=getCanvasContentRect();if(towers.length>beforeTowerCount&&state.selected){controller.x=state.selected.x;controller.y=state.selected.y;controller.screenX=r.left+controller.x/960*r.width;controller.screenY=r.top+controller.y/640*r.height;positionControllerCursor()}else if(state.selected&&state.selected!==beforeSelection){controller.x=state.selected.x;controller.y=state.selected.y;controller.screenX=r.left+controller.x/960*r.width;controller.screenY=r.top+controller.y/640*r.height;positionControllerCursor()}}
function updateController(dt){const pad=Array.from(navigator.getGamepads?.()||[]).find(Boolean);if(!pad){if(controller.connected&&ui.controller)ui.controller.textContent="Controller disconnected";controller.connected=false;const cursor=$("#s3GamepadCursor");if(cursor)cursor.hidden=true;controller.buttons=[];return}if(!controller.connected&&ui.controller)ui.controller.textContent=`${pad.id} connected`;controller.connected=true;if(!controller.initialized){const r=canvas.getBoundingClientRect();controller.screenX=r.left+r.width/2;controller.screenY=r.top+r.height/2;controller.initialized=true}const held=i=>Boolean(pad.buttons[i]?.pressed||pad.buttons[i]?.value>.55),edge=i=>held(i)&&!controller.buttons[i];const sync=()=>controller.buttons=pad.buttons.map((_,i)=>held(i));
 if(state.started&&state.intermission&&!ui.next.hidden&&state.wave===1&&!controller.firstWaveLaunchCentered){centerControllerOnElement(ui.next);controller.firstWaveLaunchCentered=true}if(!state.started){updateStageMenuSelection();const menuX=Math.abs(pad.axes[0]||0)>.65?Math.sign(pad.axes[0]):0,menuY=Math.abs(pad.axes[1]||0)>.65?Math.sign(pad.axes[1]):0,menuMove=Math.abs(menuY)>=Math.abs(menuX)?menuY:menuX;if((edge(12)||edge(14)))moveStageMenu(-1);if((edge(13)||edge(15)))moveStageMenu(1);if(menuMove&&!controller.menuAxisHeld)moveStageMenu(menuMove>0?1:-1);controller.menuAxisHeld=Boolean(menuMove);if(edge(0)||edge(9)){sync();activateStageMenu();return}sync();return}
 if(state.over){if(edge(0)||edge(9))location.reload();sync();return}
 if(state.paused){if(edge(0)||edge(9)){state.paused=false;ui.pause.hidden=true}sync();return}
 if(edge(9)){state.paused=true;ui.pause.hidden=false;sync();return}
 const rawX=Math.abs(pad.axes[0]||0)>.2?pad.axes[0]:0,rawY=Math.abs(pad.axes[1]||0)>.2?pad.axes[1]:0,ax=Math.sign(rawX)*Math.pow(Math.abs(rawX),1.35),ay=Math.sign(rawY)*Math.pow(Math.abs(rawY),1.35);controller.screenX=clamp(controller.screenX+ax*340*dt,2,innerWidth-18);controller.screenY=clamp(controller.screenY+ay*340*dt,2,innerHeight-18);positionControllerCursor();
 const types=Object.keys(specs),buildIndex=types.indexOf(state.build);if(edge(14))setBuildType(types[(buildIndex+types.length-1)%types.length]);if(edge(15))setBuildType(types[(buildIndex+1)%types.length]);if(edge(4))cycleTower(-1);if(edge(5))cycleTower(1);if(edge(2)&&state.selected){const target=document.elementFromPoint(controller.screenX,controller.screenY)?.closest(".upgrade");if(target&&!target.disabled)target.click();else ui.upgrade.click()}if(edge(3)&&state.selected){if(state.selected.relicPath)buyWeaponUpgrade(state.selected.type,state.selected.relicPath);else toast("Point at a relic branch and press X")}if(edge(1)&&controller.onCanvas)controllerBoardAction("collect");if(edge(0)){const target=document.elementFromPoint(controller.screenX,controller.screenY)?.closest(".s3-build, #s3NextWave");if(target&&!target.disabled){clearTimeout(aTapTimer);lastATap=-Infinity;target.click()}else if(controller.onCanvas){const now=performance.now(),tapX=controller.screenX,tapY=controller.screenY;if(now-lastATap<310){clearTimeout(aTapTimer);lastATap=-Infinity;controllerBoardAction("place",tapX,tapY)}else{lastATap=now;clearTimeout(aTapTimer);aTapTimer=setTimeout(()=>{if(lastATap===now){lastATap=-Infinity;controllerBoardAction("select",tapX,tapY)}},260)}}}if(edge(7)){const target=document.elementFromPoint(controller.screenX,controller.screenY)?.closest("#s3NextWave");if(target&&!target.disabled)target.click()}sync();}
function loop(t){const dt=Math.min(.04,(t-last)/1000||0);last=t;updateController(dt);update(dt);draw();requestAnimationFrame(loop)}
function ensurePulseTree(){let tree=$("#s3PulseTree");if(tree)return tree;tree=document.createElement("div");tree.id="s3PulseTree";tree.className="s3-pulse-tree";for(const path of ["rapid","heavy"]){const button=document.createElement("button");button.className="upgrade s3-path-upgrade";button.dataset.pulsePath=path;button.addEventListener("click",()=>buyPulseUpgrade(path));tree.append(button)}ui.relicUpgrade.before(tree);return tree}
function buyPulseUpgrade(path){const t=state.selected,tier=t?.relicTier||0,cost=tier+1;if(!t||t.type!=="pulse"||state.relics<cost||(t.relicPath&&t.relicPath!==path)||tier>=3)return;t.relicPath=path;t.relicTier=tier+1;t.relicSpent=(t.relicSpent||0)+cost;t.relic=true;state.relics-=cost;toast(`${pulseBranches[path][t.relicTier-1].name} installed`);updateUI()}
function branchData(type){return type==="pulse"?pulseBranches:type==="rail"?railBranches:cryoBranches}
function ensureWeaponTree(type){if(type==="pulse")return ensurePulseTree();let tree=$(`#s3${type}Tree`);if(tree)return tree;tree=document.createElement("div");tree.id=`s3${type}Tree`;tree.className="s3-pulse-tree s3-weapon-tree";for(const path of Object.keys(branchData(type))){const button=document.createElement("button");button.className="upgrade s3-path-upgrade";button.dataset.weaponPath=path;button.addEventListener("click",()=>buyWeaponUpgrade(type,path));tree.append(button)}ui.relicUpgrade.before(tree);return tree}
function buyWeaponUpgrade(type,path){if(type==="pulse")return buyPulseUpgrade(path);const t=state.selected,tier=t?.relicTier||0,cost=tier+1;if(!t||t.type!==type||state.relics<cost||(t.relicPath&&t.relicPath!==path)||tier>=3)return;t.relicPath=path;t.relicTier=tier+1;t.relicSpent=(t.relicSpent||0)+cost;t.relic=true;state.relics-=cost;toast(`${branchData(type)[path][t.relicTier-1].name} installed`);updateUI()}
function updateUI(){ui.debris.textContent=state.debris;ui.relics.textContent=state.relics;ui.wave.textContent=`${state.wave} / 20`;ui.health.textContent=`${Math.max(0,state.health)} / 20`;const t=state.selected;if(recycleConfirmTower&&recycleConfirmTower!==t)resetRecycleConfirm();if(!t){ui.selected.hidden=true;return}ui.selected.hidden=false;const st=towerStats(t),nextStats=towerStats({...t,level:t.level+1}),cost=30+t.level*22;ui.selectedName.textContent=specs[t.type].name;ui.level.textContent=t.level+(t.relic?" ★":"");ui.damage.textContent=Math.round(st.damage);ui.range.textContent=Math.round(st.range);ui.upgradeCost.textContent=`${cost} debris`;ui.upgrade.disabled=state.debris<cost;let standardDescription=$("#s3StandardDescription");if(!standardDescription){standardDescription=document.createElement("p");standardDescription.id="s3StandardDescription";standardDescription.className="s3-standard-description";ui.upgrade.after(standardDescription)}standardDescription.textContent=`Next: ${Math.round(st.damage)} → ${Math.round(nextStats.damage)} damage · ${Math.round(st.range)} → ${Math.round(nextStats.range)} range · ${st.rate.toFixed(2)}s → ${nextStats.rate.toFixed(2)}s firing interval`;ui.upgrade.title=standardDescription.textContent;let description=$("#s3RelicDescription");if(!description){description=document.createElement("p");description.id="s3RelicDescription";description.className="s3-relic-description";ui.relicUpgrade.after(description)}const tree=ensurePulseTree(),isPulse=t.type==="pulse",relicAvailable=state.relics>0||t.relic;tree.hidden=!isPulse||!relicAvailable;ui.relicUpgrade.hidden=isPulse||!relicAvailable;description.hidden=isPulse||!relicAvailable;if(isPulse){for(const button of tree.querySelectorAll("button")){const path=button.dataset.pulsePath,tier=t.relicPath&&t.relicPath!==path?0:(t.relicTier||0),locked=Boolean(t.relicPath&&t.relicPath!==path),complete=t.relicPath===path&&tier>=3,next=pulseBranches[path][Math.min(tier,2)];button.hidden=locked;button.disabled=locked||complete||state.relics<1;button.innerHTML=`<span>${complete?`${path==="rapid"?"Rapid":"Heavy"} branch complete`:next.name}</span><strong>${complete?"Complete":`Tier ${tier+1} · 1 core`}</strong><small>${complete?pulseBranches[path][2].description:next.description}</small>`}}else{ui.relicName.textContent=specs[t.type].relic;description.textContent=specs[t.type].relicDescription;ui.relicUpgrade.title=specs[t.type].relicDescription;ui.relicUpgrade.disabled=t.relic||state.relics<1;ui.relicUpgrade.querySelector("strong").textContent=t.relic?"Installed":"1 relic core"}ui.sellValue.textContent=`${Math.floor(t.spent*.65)} debris${t.relicSpent?` + ${t.relicSpent} cores`:""}`;}
const renderBaseUI=updateUI;
updateUI=function(){renderBaseUI();ui.wave.textContent=`L${state.level} · ${state.wave} / 20`;const healthLabel=$("#s3HealthLabel");if(healthLabel)healthLabel.textContent=state.level===1?"Relic Shield":state.level===2?"Frontline Strength":"Forward Bases";const t=state.selected;for(const type of ["rail","cryo"]){const existing=$(`#s3${type}Tree`);if(existing)existing.hidden=true}if(!t)return;const tree=ensureWeaponTree(t.type),data=branchData(t.type),available=state.relics>0||t.relic;tree.hidden=!available;if(t.type!=="pulse"){ui.relicUpgrade.hidden=true;const description=$("#s3RelicDescription");if(description)description.hidden=true}if(tree.hidden)return;for(const button of tree.querySelectorAll("button")){const path=button.dataset.pulsePath||button.dataset.weaponPath,tier=t.relicPath&&t.relicPath!==path?0:(t.relicTier||0),cost=tier+1,locked=Boolean(t.relicPath&&t.relicPath!==path),complete=t.relicPath===path&&tier>=3,next=data[path][Math.min(tier,2)];button.hidden=locked;button.disabled=locked||complete||state.relics<cost;button.innerHTML=`<span>${complete?`${next.name} complete`:next.name}</span><strong>${complete?"Complete":`Tier ${tier+1} · ${cost} ${cost===1?"core":"cores"}`}</strong><small>${next.description}</small>`}}
function resetRecycleConfirm(){clearTimeout(recycleConfirmTimer);recycleConfirmTower=null;ui.sell?.classList.remove("is-confirming");const label=ui.sell?.querySelector("span");if(label)label.textContent="Recycle Tower"}
function toast(text){clearTimeout(toastTimer);ui.toast.textContent=text;ui.toast.hidden=false;toastTimer=setTimeout(()=>ui.toast.hidden=true,1800)}
canvas.addEventListener("click",e=>{if(!state.started||state.paused||state.over)return;const r=getCanvasContentRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)return;const p={x:(e.clientX-r.left)*960/r.width,y:(e.clientY-r.top)*640/r.height},canCollect=controllerActionMode===null||controllerActionMode==="collect"||controllerActionMode==="select",canSelect=controllerActionMode===null||controllerActionMode==="select",canPlace=controllerActionMode===null||controllerActionMode==="place";if(canCollect){const dropIndex=drops.findIndex(d=>dist(p,d)<22);if(dropIndex>=0){const [drop]=drops.splice(dropIndex,1);if(drop.type==="relic"){state.relics++;toast("Relic core recovered") }else{state.debris+=drop.value;toast(`+${drop.value} debris`)}updateUI();return}}if(canSelect){const tower=towers.find(t=>dist(p,t)<25);if(tower){state.selected=tower;updateUI();return}}if(!canPlace){toast(controllerActionMode==="collect"?"No relic core here":"No tower or relic here");return}const s=specs[state.build],usesPaintedZones=state.level===2||state.level===3,insidePaintedZone=state.level===2?levelTwoBuildZones.some(zone=>pointInPolygon(p,zone)):state.level===3?levelThreeBuildZones.some(zone=>pointInPolygon(p,zone)):true,nearPath=state.level===2?isNearActivePathClearance(p,30):state.level===3?isNearActivePathClearance(p,30):!usesPaintedZones&&isNearActivePath(p),outsidePaintedZone=usesPaintedZones&&!insidePaintedZone;if(nearPath||outsidePaintedZone||state.level===1&&p.x>775&&p.y>205&&p.y<455){toast(outsidePaintedZone?"Build inside a cyan zone":"That space must remain clear");return}if(towers.some(t=>dist(p,t)<42)){toast("Towers need more room");return}if(state.debris<s.cost){toast("Not enough debris");return}state.debris-=s.cost;const t={type:state.build,x:p.x,y:p.y,level:1,relic:false,relicPath:null,relicTier:0,relicSpent:0,cool:0,spent:s.cost};towers.push(t);state.selected=t;updateUI();});
document.querySelectorAll(".s3-build").forEach(b=>b.addEventListener("click",()=>setBuildType(b.dataset.tower)));
ui.upgrade.addEventListener("click",()=>{const t=state.selected,c=30+t.level*22;if(t&&state.debris>=c){state.debris-=c;t.spent+=c;t.level++;resetRecycleConfirm();updateUI()}});ui.relicUpgrade.addEventListener("click",()=>{const t=state.selected;if(t&&t.type!=="pulse"&&!t.relic&&state.relics){state.relics--;t.relic=true;t.relicSpent=(t.relicSpent||0)+1;resetRecycleConfirm();toast(`${specs[t.type].relic} installed`);updateUI()}});ui.sell.addEventListener("click",()=>{const t=state.selected;if(!t)return;if(recycleConfirmTower!==t){recycleConfirmTower=t;ui.sell.classList.add("is-confirming");const label=ui.sell.querySelector("span");if(label)label.textContent="Click again to recycle";toast("Click recycle again to confirm");clearTimeout(recycleConfirmTimer);recycleConfirmTimer=setTimeout(resetRecycleConfirm,2600);return}resetRecycleConfirm();state.debris+=Math.floor(t.spent*.65);state.relics+=t.relicSpent||0;towers=towers.filter(x=>x!==t);state.selected=null;updateUI()});
const startActions=document.createElement("div"),startButton=$("#s3StartButton");startActions.className="s3-start-actions";startButton.before(startActions);startActions.append(startButton);for(const level of [1,2,3]){const debugButton=document.createElement("button");debugButton.id=`s3DebugLevel${level}`;debugButton.className="s3-debug-button";debugButton.textContent=`Debug: Level ${level}`;debugButton.addEventListener("click",()=>startDebugLevel(level));startActions.append(debugButton)}startButton.addEventListener("click",()=>{state.started=true;ui.start.hidden=true;prepareFirstWave(false)});ui.next.addEventListener("click",beginWave);$("#s3RestartButton").addEventListener("click",()=>location.reload());$("#s3ResumeButton").addEventListener("click",()=>{state.paused=false;ui.pause.hidden=true});addEventListener("keydown",e=>{if(e.key.toLowerCase()==="p"&&state.started&&!state.over){state.paused=!state.paused;ui.pause.hidden=!state.paused}});reset();const debugLevel=Number(new URLSearchParams(location.search).get("debugLevel"));if([1,2,3].includes(debugLevel))startDebugLevel(debugLevel);requestAnimationFrame(loop);
window.addEventListener("gamepadconnected",event=>{controller.connected=true;controller.initialized=false;controller.buttons=[];const cursor=ensureControllerCursor();cursor.hidden=false;if(ui.controller)ui.controller.textContent=`${event.gamepad.id} connected`});
window.addEventListener("gamepaddisconnected",()=>{controller.connected=false;controller.initialized=false;controller.buttons=[];const cursor=$("#s3GamepadCursor");if(cursor)cursor.hidden=true;if(ui.controller)ui.controller.textContent="Controller disconnected"});









